### ISSUE TITLE
Consider moving to the graphql-ruby org?

### ISSUE THREAD

**Issue by dblock** [exAspArk/graphql-errors#1]
Would maintainers consider moving this to a `graphql-ruby` org? Similar to https://github.com/slack-ruby or https://github.com/alexa-js or https://github.com/ruby-grape? I am happy to cheerlead. Owners will be all maintainers of this and other projects that would be the "founding members". It could become a home for projects such as this one and others, such as https://github.com/exAspArk/graphql-errors and https://github.com/ashkan18/graphlient.

This would make GraphQL ruby projects much more discoverable.

It seems to exist, https://github.com/graphql-ruby, but I am sure we can reclaim it from Github.

Related: https://github.com/rmosolgo/graphql-ruby/issues/1034

**Comment by exAspArk** [comment]
Hey @dblock,

Thanks a lot for the proposal! 

I'll be watching for updates in the rmosolgo/graphql-ruby#1034 PR. Without the main [graphql-ruby](https://github.com/rmosolgo/graphql-ruby) repository in the organization it probably won't make sense :)

**Comment by exAspArk** [comment]
Closing the issue as it seems like the creator of [graphql-ruby](https://github.com/rmosolgo/graphql-ruby) doesn't want to move it into a separate organization.

Thank you!
