### ISSUE TITLE
Validation errors from model don't show

### ISSUE THREAD

**Issue by RolandStuder** [exAspArk/graphql-errors#10]
This is probably me missunderstanding how errors work in Rails, but I installed the gem, and added the configuration like suggested:

```
GraphQL::Errors.configure(ResponsiveOrgSchema) do
  rescue_from ActiveRecord::RecordNotFound do |exception|
    GraphQL::ExecutionError.new("RecordNotFound")
  end

  rescue_from ActiveRecord::RecordInvalid do |exception|
    GraphQL::ExecutionError.new(exception.record.errors.full_messages.join("\n"))
  end

  rescue_from StandardError do |exception|
    GraphQL::ExecutionError.new("Please try to execute the query for this field later")
  end
end
```

This works nicely for `ActiveRecord::RecordNotFound` and `StandardError`, but I get no errors when it fails validation (`ActiveRecord::RecordInvalid`). I call the create method of the model directly from the resolver.

```
resolve -> (obj, args, ctx) {
  Foo.create(something: args["bar"])      
}

```

What do I have to do, what am I missing? I assume the problem is, that the Foo.create just returns nil, instead of actually throwing an error. So how do I get the validation errors.

I am on Rails 5.1.6,    graphql (1.7.14),     graphql-errors (0.2.0).

**Comment by geshafer** [comment]
@RolandStuder `#create` doesn't raise an exception, you'll have to use [`create!`](https://apidock.com/rails/v4.2.7/ActiveRecord/Persistence/ClassMethods/create%21) to raise the `RecordInvalid` exception.

**Comment by exAspArk** [comment]
Yeah, @geshafer is absolutely right :)

If you'd like to raise and catch the `ActiveRecord::RecordInvalid` exception, you should use `Foo.create!(attributes)` with `!`.
