### ISSUE TITLE
Compatibility with class based Graphql-ruby?

### ISSUE THREAD

**Issue by ghost** [exAspArk/graphql-errors#17]
This seems to not work anymore:

```ruby
# frozen_string_literal: true

class SayduckSchema < GraphQL::Schema
  # ...
end

GraphQL::Errors.configure(SayduckSchema) do
  rescue_from(ActiveRecord::RecordNotFound) do |_exception|
    GraphQL::ExecutionError.new(errors, extensions: { code: :NOT_FOUND })
  end
end

SayduckSchema.graphql_definition
```

```bash
  ↳ app/graphql/sayduck_schema.rb:56
Completed 404 Not Found in 10ms (ActiveRecord: 0.9ms)



ActiveRecord::RecordNotFound (Couldn't find Product with [WHERE "products"."uuid" = $1]):

app/graphql/sayduck_schema.rb:56:in `block in object_from_id'
app/graphql/sayduck_schema.rb:48:in `then'
app/graphql/sayduck_schema.rb:48:in `object_from_id'
app/graphql/field_types/node_field.rb:18:in `resolve'
app/graphql/sayduck_schema.rb:22:in `execute_from_hash'
app/controllers/graphql_controller.rb:32:in `execute_query'
app/controllers/graphql_controller.rb:10:in `execute'
```

What am I missing here?

**Comment by exAspArk** [comment]
Hi @sayduck-daniel,

Which `graphql` gem version do you use? It worked with v1.8:

https://github.com/exAspArk/graphql-errors/blob/dd1d4e3bbcf0162152e08b966d1a379472441796/spec/fixtures/schema.rb#L123-L133

**Comment by ghost** [comment]
I’m using 1.9.4 and using 

```ruby
class SayduckSchema < GraphQL::Schema
  max_depth 10

  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST
  use GraphQL::Subscriptions::ActionCableSubscriptions
  use GraphQL::Tracing::ScoutTracing
  use GraphQL::Backtrace
  use BatchLoader::GraphQL

  query Types::QueryType
  mutation Types::MutationType
  subscription Types::SubscriptionType
End
```

**Comment by exAspArk** [comment]
Oh, I see. You're using `GraphQL::Execution::Interpreter` which is an experimental feature:

![image](https://user-images.githubusercontent.com/577441/56219310-848e6080-6034-11e9-84c9-e9963e053cdf.png)

`graphql-errors` doesn't support it yet. I'll add support once the new `graphql` became stable to avoid any potential breaking changes.

**Comment by ghost** [comment]
I see @knshiro has created a pull request solving this. Any chance we could have it on the gem?

**Comment by knshiro** [comment]
Just realized I still need to work on that PR...

**Comment by ghost** [comment]
This issue is still open tho

**Comment by knshiro** [comment]
Just a quick precision though: this gem works with class based graphql-ruby. The only thing it doesn't work with is `GraphQL::Execution::Interpreter`.

**Comment by raysuelzer** [comment]
@knshiro  I see you closed the PR you had for fixing this without a merge. Is there an issue with the ruby-graphql gem that is causing issues in implementing this feature?  The current recommendation from the maintainer of the graph library is to be using the new interpreter.

**Comment by knshiro** [comment]
In the previous implementation there was a way to inject a try catch around the block that executed the whole code resolving any field even in the case of lazy loaded code (e.g. for batch). With the interpreter the only hook you get can not catch a lazily resolved field error.

**Comment by raysuelzer** [comment]
The thing that I noticed failing in the tests was that the path was incorrect.  Is that a symptom of the issue you described above. @knshiro
