### ISSUE TITLE
Errors raised via GraphQL::ExecutionError aren't caught by github/graphql-client

### ISSUE THREAD

**Issue by dblock** [exAspArk/graphql-errors#2]
I'm trying to figure out what the expected behavior is in https://github.com/github/graphql-client/pull/132. It looks like the catch-all errors provided by this library aren't treated as errors because they don't have a path.

What's supposed to happen per spec? Is this library not setting a path correctly?

**Comment by exAspArk** [comment]
To be honest, I've never used `graphql-client` / `graphlient`.

If you add something like:

```ruby
rescue_from StandardError do |e|
  puts e.inspect
  puts e.backtrace
end
```

Is there any backtrace? Or the exception is happening before the GraphQL part?

**Comment by dblock** [comment]
Let me restate the issue: grahql-errors recommends producing a catch-all  `GraphQL::ExecutionError`, which returns a bunch of things in `errors` as it should. Because those errors don't have a path at least one popular client seems to not understand what it's getting, which begs the question of whether graphql-errors is returning the wrong thing not to spec. But I don't quite understand what's supposed to be returned there.

**Comment by exAspArk** [comment]
Yeah, so, the `GraphQL::ExecutionError` comes from the [graphql-ruby](https://github.com/rmosolgo/graphql-ruby) library. It should add a `path` for the error automatically.

If you use other browser tools like GraphiQL or [GraphQL Playground](https://www.graphqlbin.com/RVIn):

![image](https://user-images.githubusercontent.com/577441/32178796-10ab9562-bd64-11e7-8837-15bd62020b33.png)

And send the request, will it return `path` or not? (to understand whether it's a problem with clients or not).

If the `path` is empty, is there any way to reproduce it, so I can try to debug it?

**Comment by dblock** [comment]
The path is there, the issue is internal to graphql-client, I updated that PR with a repro that doesn't involve graphql-errors. We can close this.
