### ISSUE TITLE
There is something like "NotAuthorizedError"?

### ISSUE THREAD

**Issue by ghost** [exAspArk/graphql-errors#4]
There is something like:

```
  rescue_from NotAuthorizedError do |exception|
    GraphQL::ExecutionError.new("You are not authorized!")
  end
```

**Comment by exAspArk** [comment]
Sorry, what do you mean? 

If you use https://github.com/exaspark/graphql-guard#error-handling, it'll raise `GraphQL::Guard::NotAuthorizedError` by default.

So, you can rescue the exception.

**Comment by ghost** [comment]
And what about status code, like 401?
